### ISSUE TITLE
Clinking on error link opens new tab of already opened file

### ISSUE THREAD

**Issue by samarthiith** [GAMS-dev/studio#169] opened 2018-08-29 08:45 UTC
On clicking the link to error, a new tab is created with the file even if the file is already open. Would be better if it directs to already opened file. 
I am using MacOS X.

**Comment by rgoltermann** [comment] 2018-08-29 09:11
hello and thank you for contributing!
so far i was not able to reproduce your issue. please provide some additional information.
- your GAMS Studio version number (which you can find in the top menu under "studio" > "About studio")
- your MacOS version
- which link do you mean exactly, are you clicking on links in the log or on underlined errors in the editor?

**Comment by samarthiith** [comment] 2018-08-29 12:18
Hi! thanks for responding

- GAMS Studio 0.9.2 
- MacOS High Sierra 10.13.6
- The link in the logs for example:
![screen shot 2018-08-29 at 2 14 30 pm](https://user-images.githubusercontent.com/9819174/44786910-f1ccae80-ab95-11e8-8957-ae5bd3a32fef.png)
once a new file has been opened upon clicking this, clicking on next error leads to this file (new open one), any changes made here then causes the already opened file to update.

**Comment by rgoltermann** [comment] 2018-08-31 07:53
Hi and thank you for the additional information.
Studio opening a new tab on each click is definitely not intended behavior but we were not able to reproduce this behavior ourselves. so this issue could be related to your setup.

in Studio v0.9.2 we are comparing the paths of files as strings. if these are somehow different but still point to the same file studio does not recognize that the file is already open in another tab and would open another one. this will be fixed in the next update.
another potential problem could be that you are using symlinks in your project which are not properly resolved by studio, leading to a similar situation as mentioned above.

you can test this by hovering over the file in the studios project explorer. if the tooltip shows a different link than the link you click in the log, although it should be the same file, than one of the statements above is true.

**Comment by rgoltermann** [comment] 2018-11-29 10:59
Hello Samarth,
could you manually update Studio to the latest version (available here: https://github.com/GAMS-dev/studio/releases) and report if this issue still persists?

**Comment by rgoltermann** [comment] 2019-03-27 16:46
we were not able to reproduce this and are assuming that this was fixed with an update.  
if this issue should resurface please feel free to contact us again.

**Closed by rgoltermann** 2019-03-27 16:46 UTC
Labels: bug
