### ISSUE TITLE
output (log) window blocks complete app

### ISSUE THREAD

**Issue by universal** [GAMS-dev/studio#179] opened 2019-03-13 09:17 UTC
Hello,

i'm using the studio app on ubuntu 18.04 from the 26.1 release. I'm solving many small model instances one after another and the log window slows down a lot and the complete studio becomes unresponsive. This already happens for a small trial run of 200 instances. The log gets stuck at some point at for example iteration 41 and the next update then jumps to 63, and so on... Restarting the app has no observeable effect. 

I can easily circumvent this by running the code in question from the terminal, where there is no slow-down happening and it just happily flys by.

If there is any information that might be helpful from my side, I will do my best to supply it :-)

**Comment by rgoltermann** [comment] 2019-03-14 09:25
Hello and thank you for you report.  
We are working on resolving this performance issue and will post an update here when we have a release that fixes this.

**Comment by MrMontag** [comment] 2019-11-04 10:00
The issue is solved in the latest GAMS Studio 0.13.1.

**Closed by MrMontag** 2019-11-04 10:00 UTC
Labels: bug
